### ISSUE TITLE
APIs definition

### ISSUE THREAD

**Issue by conke** [debug-live/ladder#2]

**Comment by conke** [comment]
## Get language list
url: "/language"
method: GET
input: N/A
output: 
status: SUCCESS/FAIL
data: [lang1, lang2, ...]

language object:

field | description | type | example
-----|-----------|------|----
id  | lang code | string | java
desc | lang description | string | Java

example:
[{id: "java", desc: "sdkman, Java, maven, gradle, ..."}, {id: "cxx", desc: "cmake, cxx"}]

## Put language list
url: "/language"
method: POST

input: [lang1 id, lang2 id, ...]

output: 
status: SUCCESS/FAIL
data: N/A

**Comment by sandyzhou** [comment]
Update "Put language list".

## Put language list

url: "`/build-status`"
method: POST

input: `{list: [lang1 id, lang2 id, ...]}`

output:
status: SUCCESS/FAIL
data: N/A
